# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\ConsoleApp1\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.BinariesDirectory)\App1'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\ConsoleApp2\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.BinariesDirectory)\App2'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'SnowCaitOAuth'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
- script: |
    ls -la ConsoleApp1
    echo $(Build.SourcesDirectory)
    ls -la $(Build.SourcesDirectory)
    echo $(Build.BinariesDirectory)
    ls -la $(Build.BinariesDirectory)
    echo $(Build.ArtifactStagingDirectory)
    ls -la $(Build.ArtifactStagingDirectory)
